# regras --------------------------
# padrão para o fundo da tela -------
<BGwhite@BoxLayout>:
    orientation: 'vertical'
    canvas.before:
        Color:
            rgba: ( 1, 1, 1, 1 )
        Rectangle: 
            pos: self.pos
            size: self.size

# padrão para input -------
<BoxInput@BoxLayout>:
    size_hint_y: None
    height: dp(40)
    padding: dp(6) 
    spacing: dp(8)

    canvas.before:
        Color:
            rgba: 0.9, 0.9, 0.9, 1
        RoundedRectangle:
            pos: self.x, self.y
            size: self.size
            radius: [10]

#padrão dos botões de entrada ------
<EnterButton@Button>:
    background_normal: ''
    background_down: ''
    background_color: 0, 0, 0, 0  
    color: 1, 1, 1, 1  

    canvas.before:
        Color:
            rgba: ( 0, 0.5, 0.9, 1 )
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [10]

#
#
# page manager______________________
<ControllerTelas>:
    LoginPage:
        name: ('loginpage')

    RegisterPage:
        name: ('registerpage')

    HomePage:
        name: ('homepage')
        


# Screen login _________________________
<LoginPage>:
    
    BGwhite:
        id: loginLayout

        padding: dp(50)
        spacing: dp(30)
        
        Image: 
            size_hint_y: 0.5
            source:'images/listIcon copy.png'

        BoxInput:

            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source:'images/listIcon copy.png'
            
            TextInput:
                id: inputMail
                hint_text: "E-mail"
                multiline: False

                background_normal: ''
                background_active: ''
                background_color: (0, 0, 0, 0)

                size_hint_x: 0.9
                padding: [10, 5]
        
        BoxInput:
            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source:'images/listIcon copy.png'  

            TextInput:
                id: inpuPassword
                hint_text: "Senha"
                multiline: False

                background_normal: ''
                background_active: ''
                background_color: (0, 0, 0, 0)

                size_hint_x: 0.9
                padding: [10, 5]
        
        BoxLayout:
            size_hint_y: 0.2
            spacing: dp(5)
            EnterButton:
                id: btnAccess
                size_hint_y: None
                size_hint_x: 0.4
                height: dp(40)
                text: 'Entrar'
                on_release: app.root.current= 'homepage'

            EnterButton:
                id: btnReirect
                size_hint_y: None
                size_hint_x: 0.2
                height: dp(40)
                text: 'cadastrar'
                on_release: app.root.current= 'registerpage'



# Screen cadastro ____________________________________
<RegisterPage>:
    
    BGwhite: 
        id: registerLayout

        padding: dp(50)
        spacing: dp(30)

        Image: 
            source:'images/listIcon copy.png'


        # name user________
        BoxInput: 
            
            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source:'images/listIcon copy.png'

            TextInput: 
                id: inputMail
                hint_text: "E-mail"
                multiline: False

                background_normal: ''
                background_active: ''
                background_color: (0, 0, 0, 0)

                size_hint_x: 0.9
                padding: [10, 5] 


        # id user_______
    
            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source: 'images/listIcon copy.png'
            
            TextInput: 
                id: inputNameUser
                multiline: False
                hint_text: "Nome"

                background_normal: ''
                background_active: ''
                background_color: (0, 0, 0, 0)

                size_hint_x: 0.8
                padding: [10, 5]

        
        # password user______
        BoxInput:
            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source: 'images/listIcon copy.png'

            TextInput:
                id: inputPassword
                password: True
                multiline: False
                hint_text: "Senha"

                background_normal: ''
                background_active: ''
                background_color: 0, 0, 0, 0

                size_hint_x: 0.8
                padding: [10, 5]
                

        EnterButton: 
            
            size_hint_y: None
            text: "Criar conta"
            height: dp(40)
            on_release: app.root.current ='homepage'



# Screen núcleos familiares ____________________________________
<HomePage>: 
    BGwhite:
        id: homeLayout

        FloatLayout:
            size_hint_y: 0.09
            orientation: 'vertical'

            ActionBar:
                pos_hint: {'top': 1}
                ActionView:
                    ActionPrevious:
                        on_release: app.root.current= 'loginpage'

        ScrollView:
            do_scroll_x: False

            BoxLayout:
                id: containerNucleos
                orientation: 'vertical'

                padding: 10
        
        BoxLayout:
            size_hint_y: 0.1
            padding: 60, 4   

            Button:
                text: "adicionar" 
                on_release: root.insertModal()

        
# entidades --------------------
<Nucleo>:
    id: nucleo
    size_hint_y: None
    height: dp(200)
    BoxLayout:
        Image:
            id: taskImage
            source: 'images/listIcon copy.png'

        BoxLayout:
            orientation: 'vertical'
            Label:
                id: nucleoTitle
                text: "tarefa"
                font_size: 35

            Label:
                id: taskDescription
                text: "09/09/2009"


<ModalNucleo>:
    size_hint: 0.9, 0.6 # o widget ocupa porcentagem da tela
    auto_dismiss: True # tenho que chamado o dismiss() 
    
    BoxLayout:
        id: modalNucleo
        padding: 30
        spacing: 10
        orientation: 'vertical'

        Label:
            text: "novo nucleo" 
            size_hint_y: None
            height: dp(30)

        BoxLayout:
            size_hint_y: None
            Image:
                source: 'images/listIcon copy.png'
                allow_stretch: True
                size_hint_x: 1
                size_hint_y: None

            TextInput:
                id: inputTitle
                hint_text: "titulo"    
                size_hint_y: None
                size_hint_x: 2
                height: dp(40)
                
        Label:
            text: 'descrição'
            size_hint_y: None
            height: dp(20)

        TextInput:
            id: inputDescription
            hint_text: "Descrição"
            size_hint_y: None
            height: dp(40)
        
        Button:
            size_hint_y: 1
            text: 'Criar'
            on_release: 


