# regras --------------------------
<BoxInput@BoxLayout>:
    size_hint_y: None
    height: dp(40)
    padding: dp(6) 
    spacing: dp(8)

    canvas.before:
        Color:
            rgba: 0.9, 0.9, 0.9, 1
        RoundedRectangle:
            pos: self.x, self.y
            size: self.size
            radius: [10]

<EnterButton@Button>:
    background_normal: ''
    background_down: ''
    background_color: 0, 0, 0, 0  
    color: 1, 1, 1, 1  

    canvas.before:
        Color:
            rgba: ( 0, 0.5, 0.9, 1 )
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [10]

# page manager______________________
<ControllerTelas>:
    LoginPage:
        name: ('loginpage')

    RegisterPage:
        name: ('registerpage')

    Screen:
        name: ('home')
        Button:
            text: 'teste'
            on_release: root.current= 'loginpage'
        

# Screen login _________________________
<LoginPage>:
    BoxLayout:
        id: login
        orientation: 'vertical'
        padding: dp(50)
        spacing: dp(30)
        

        canvas.before:
            Color:
                rgba: ( 1, 1, 1, 1 )
            Rectangle: 
                pos: self.pos
                size: self.size

        Image: 
            size_hint_y: 0.5
            source:'images/listIcon copy.png'

        BoxInput:

            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source:'images/listIcon copy.png'
            
            TextInput:
                id: inputMail
                hint_text: "E-mail"
                multiline: False

                background_normal: ''
                background_active: ''
                background_color: (0, 0, 0, 0)

                size_hint_x: 0.9
                padding: [10, 5]
        
        BoxInput:
            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source:'images/listIcon copy.png'  

            TextInput:
                id: inpuPassword
                hint_text: "Senha"
                multiline: False

                background_normal: ''
                background_active: ''
                background_color: (0, 0, 0, 0)

                size_hint_x: 0.9
                padding: [10, 5]
        
        BoxLayout:
            size_hint_y: 0.2
            spacing: dp(5)
            EnterButton:
                id: btnAccess
                size_hint_y: None
                size_hint_x: 0.4
                height: dp(40)
                text: 'Entrar'
                on_release: app.root.current= 'home'

            EnterButton:
                id: btnReirect
                size_hint_y: None
                size_hint_x: 0.2
                height: dp(40)
                text: 'cadastrar'
                on_release: app.root.current= 'registerpage'

# Screen cadastro _________________________
<RegisterPage>:
    
    BoxLayout: 
        id: register
        orientation: 'vertical'
        padding: dp(50)
        spacing: dp(30)

        canvas.before:
            Color:
                rgba: ( 1, 1, 1, 1 ) 
            Rectangle:
                pos: self.pos
                size: self.size

        Image: 
            source:'images/listIcon copy.png'


        # name user______________________
        BoxInput: 
            
            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source:'images/listIcon copy.png'

            TextInput: 
                id: inputMail
                hint_text: "E-mail"
                multiline: False

                background_normal: ''
                background_active: ''
                background_color: (0, 0, 0, 0)

                size_hint_x: 0.9
                padding: [10, 5] 


        # id user______________________
        BoxInput: 
    
            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source: 'images/listIcon copy.png'
            
            TextInput: 
                id: inputNameUser
                multiline: False
                hint_text: "Nome"

                background_normal: ''
                background_active: ''
                background_color: (0, 0, 0, 0)

                size_hint_x: 0.8
                padding: [10, 5]

        
        # password user______________________
        BoxInput:
            Image:
                size_hint_x: 0.2
                allow_stretch: True
                source: 'images/listIcon copy.png'

            TextInput:
                id: inputPassword
                password: True
                multiline: False
                hint_text: "Senha"

                background_normal: ''
                background_active: ''
                background_color: 0, 0, 0, 0

                size_hint_x: 0.8
                padding: [10, 5]
                

        EnterButton: 
            
            size_hint_y: None
            text: "Criar conta"
            height: dp(40)
            on_release: app.root.current ='home'




