# padrão para o fundo da tela -------
<BGwhite@BoxLayout>:
    orientation: 'vertical'
    canvas.before:
        Color:
            rgba: ( 1, 1, 1, 1 )
        Rectangle: 
            pos: self.pos
            size: self.size

<BGwhiteGreen@BoxLayout>:
    orientation: 'vertical'
    canvas.before:
        Color:
            rgba: (0.92, 0.95, 0.96, 1)
        Rectangle: 
            pos: self.pos
            size: self.size

# padrão para input -------
<BoxInput@BoxLayout>:
    size_hint_y: None
    height: dp(40)
    padding: dp(6) 
    spacing: dp(8)

    canvas.before:
        Color:
            rgba: 0.9, 0.9, 0.9, 1
        RoundedRectangle:
            pos: self.x, self.y
            size: self.size
            radius: [10]



#padrão dos botões de entrada ------
<EnterButton@Button>:
    
    background_normal: ''
    background_down: ''
    background_color: 0, 0, 0, 0  
    color: 1, 1, 1, 1  

    canvas.before:
        Color:
            rgba: ( 0, 0.5, 0.9, 1 )
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [10]



#padrão textinputs de um modal ------
<TextInputModal@TextInput>:
    height: dp(10)
    padding: [0, 4]
    background_normal: ''
    background_active: ''
    background_color: (0, 0, 0, 0)



#padrão button behavior ------
<ItenBehavior@ButtonBehavior+BoxLayout>:
    canvas.before:
        Color: 
            rgba: (1, 1, 1, 1) if self.state == 'normal' else (0.7, 0.7, 0.7, 1)
        Rectangle: 
            size: root.size 
            pos: root.pos 

#