#: include app/interface/kvLang/Components.kv

# Modal de criação de tarefas
<ModalTask>:
    size_hint: 0.9 , 0.7
    auto_dismiss: True

    BGwhite:
        id: modalTask
        padding: [20, 10]
        spacing: 5

        Label:
            text: "Nova Tarefa" 
            font_size: 25
            halign: "left"
            text_size: self.size
            size_hint_y: None
            height: dp(30)
            color: (0, 0, 0, 1)


        # campo de nome ------------------
        BoxLayout:
            size_hint_y: 0.5
            height: 60
            #padding: [0, 10]

            Image:
                source: 'dev/static/images/ui_user_profile_avatar_person_icon_208734.png'
                allow_stretch: True
                size_hint_x: 0.7
                size_hint_y: 1

            TextInputModal:
                id: inputTitle
                hint_text: "titulo"
                multiline: False    
                size_hint_y: None
                pos_hint_y: 1
                size_hint_x: 2
                height: dp(30)
                canvas.after:
                    Color:
                        rgba: 0.6, 0.6, 0.6, 1 
                    Line:
                        points: [self.x, self.y , self.right, self.y]  
                        width: 1.2                

        # campo para inserir data -----------------
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 1
            spacing: dp(5)
            padding: [0, 0]
            Label: 
                text: 'Prazo de conclusão'
                font_size: 20
                color: (0, 0, 0, 1)
                halign: 'left'
                text_size: self.size
                size_hint_y: 0.5
                height: dp(20)

            TextInputModal:
                id: inputDate
                hint_text: "dd/mm/aaaa"
                multiline: False    
                size_hint_y: None
                pos_hint_y: 1
                size_hint_x: 1
                height: dp(30)
                canvas.after:
                    Color:
                        rgba: 0.6, 0.6, 0.6, 1 
                    Line:
                        points: [self.x, self.y , self.right, self.y]  
                        width: 1.2

        # campo para a inserção de responsável -------------
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 1
            spacing: dp(5)
            padding: [0, 10]
            Label: 
                text: 'Responsável'
                font_size: 20
                color: (0, 0, 0, 1)
                halign: 'left'
                text_size: self.size
                size_hint_y: 0.5
                height: dp(20)

            TextInputModal:
                id: inputPerson
                hint_text: "integrante@email.com"
                multiline: False    
                size_hint_y: None
                pos_hint_y: 1
                size_hint_x: 1
                height: dp(30)
                canvas.after:
                    Color:
                        rgba: 0.6, 0.6, 0.6, 1 
                    Line:
                        points: [self.x, self.y , self.right, self.y]  
                        width: 1.2

        # Campo de descrição --------------   
        BoxLayout: 
            orientation: 'vertical'
            size_hint_y: 1
            spacing: dp(5)
            padding: [0, 10]
            Label: 
                text: 'Descrição'
                font_size: 20
                color: (0, 0, 0, 1)
                halign: 'left'
                text_size: self.size
                size_hint_y: 0.5
                height: dp(20)

            TextInputModal: 
                id: inputDescription
                hint_text: "Descrição"
                multiline: True
                size_hint_y: 1
                height: dp(20)
                padding: dp(5)
                color: (1, 1, 1, 1)

                canvas.before: 
                    Color:  
                        rgba: (0.5, 0.5, 0.5, 1)
                    Line: 
                        rounded_rectangle:(self.x, self.y, self.width, self.height, 5)
                        width: 1.02

                
        # bottões para criar e cancelar -------------
        BoxLayout:
            spacing: dp(5)
            size_hint_y: 0.5
            EnterButton:
                size_hint_x: 2
                text: 'Criar'
                on_release: app.root.get_screen("taskspage").insertTask() , root.dismiss()
            
            Button:
                text: 'Cancelar'
                size_hint_x: 1
                on_release: root.dismiss()

                background_normal: ''
                background_down: ''
                background_color: 0, 0, 0, 0  
                color: 1, 1, 1, 1
                canvas.before:
                    Color: 
                        rgba: 0.6, 0.6, 0.6, 1
                    RoundedRectangle: 
                        pos: self.pos
                        size: self.size
                        radius: [10]

<DatePicker>:
    size_hint: 0.5 , 0.5
    BoxLayout:
        Button:
            text: 'dia 1'
        Button:
            text: 'dia 2'