#: include app/interface/kvLang/Components.kv

<ModalNucleo>:
    #BoxLayout:
        
    size_hint_y: None
    height: dp(60)

    size_hint: 0.9, 0.6 # o widget ocupa porcentagem da tela
    auto_dismiss: False # tenho que chamar o dismiss() 

    BGwhite:
        id: modalNucleo
        padding: [20, 10]
        spacing: 10

        Label:
            text: "Novo núcleo" 
            font_size: 25
            halign: "left"
            text_size: self.size
            size_hint_y: None
            height: dp(30)
            color: (0, 0, 0, 1)


        # campo de nome ------------------
        BoxLayout:
            size_hint_y: None
            height: 60
            #padding: [0, 10]

            Image:
                source: 'dev/static/images/ui_user_profile_avatar_person_icon_208734.png'
                allow_stretch: True
                size_hint_x: 0.7
                size_hint_y: 1

            TextInputModal:
                id: inputTitle
                hint_text: "titulo"
                multiline: False    
                size_hint_y: None
                pos_hint_y: 1
                size_hint_x: 2
                height: dp(30)
                canvas.after:
                    Color:
                        rgba: 0.6, 0.6, 0.6, 1 
                    Line:
                        points: [self.x, self.y , self.right, self.y]  
                        width: 1.2                


        # Divisoria entre os campos ---------------
        BoxLayout: 
            height: 5
            size_hint_y: 0.2
            canvas.before:
                Color: 
                    rgba: (0.5, 0.5, 0.5, 1)
                Line: 
                    points: (self.x , self.y, self.right, self.y)
                    width: 1.2


        # Campo de descrição --------------   
        BoxLayout: 
            orientation: 'vertical'
            size_hint_y: 2
            spacing: dp(5)
            padding: [0, 10]
            Label: 
                text: 'Descrição'
                font_size: 25
                color: (0, 0, 0, 1)
                halign: 'left'
                text_size: self.size
                size_hint_y: 0.5
                height: dp(20)

            TextInputModal: 
                id: inputDescription
                hint_text: "Descrição"
                multiline: True
                size_hint_y: 2
                height: dp(40)
                padding: dp(5)
                color: (1, 1, 1, 1)

                canvas.before: 
                    Color:  
                        rgba: (0.5, 0.5, 0.5, 1)
                    Line: 
                        rounded_rectangle:(self.x, self.y, self.width, self.height, 5)
                        width: 1.02

                
        # bottões para criar e cancelar -------------
        BoxLayout:
            spacing: dp(5)
            size_hint_y: 0.5
            EnterButton:
                size_hint_x: 2
                text: 'Criar'
                on_release: app.root.get_screen("homepage").insertNucleo() , root.dismiss()
            
            Button:
                text: 'Cancelar'
                size_hint_x: 1
                on_release: root.dismiss()

                background_normal: ''
                background_down: ''
                background_color: 0, 0, 0, 0  
                color: 1, 1, 1, 1
                canvas.before:
                    Color: 
                        rgba: 0.6, 0.6, 0.6, 1
                    RoundedRectangle: 
                        pos: self.pos
                        size: self.size
                        radius: [10]