#: include app/interface/kvLang/Components.kv

<Nucleo>:
    id: nucleo
    size_hint_y: None
    height: dp(60)
    
    canvas.before:
        Color:
            rgba: 1,1,1,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [10]

    ItenBehavior:
        padding: 0
        on_release: 
            app.root.current= 'taskspage'
            app.root.get_screen('taskspage').open_TaskPage(root.idnucleo)
            app.root.get_screen('taskspage').searchTasks_byNucleo()

        Image:
            size_hint_x: 0.5
            id: nucleoImage
            source: 'dev/static/images/ui_user_profile_avatar_person_icon_208734.png'

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 2

            Label:
                id: nucleoTitle
                text: "nome núcleo"
                font_size: 20
                halign: 'left'
                text_size: self.size
                color: (0, 0, 0, 1)

            Label:
                id: taskDescription
                text: "descrição"
                halign: 'left'
                valign: 'top'
                text_size: self.size
                color: (0.4, 0.4, 0.4, 1)