#: include app/interface/kvLang/Components.kv

<Nucleo>:
    id: nucleo
    size_hint_y: None
    height: dp(60)
    ItenBehavior:
        padding: 0
        on_release: app.root.current= 'taskspage'

        canvas.before:
            Color:
                rgba: (0.5, 0.5, 0.5, 1)
            Line:
                rectangle: (app.root.get_screen("homepage").ids.containerNucleos.x, self.y, app.root.get_screen("homepage").ids.containerNucleos.width, self.height)
                width: 1

        Image:
            size_hint_x: 0.5
            id: nucleoImage
            source: 'dev/static/images/ui_user_profile_avatar_person_icon_208734.png'

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 2

            Label:
                id: nucleoTitle
                text: "nome núcleo"
                font_size: 20
                halign: 'left'
                text_size: self.size
                color: (0, 0, 0, 1)

            Label:
                id: taskDescription
                text: "descrição"
                halign: 'left'
                valign: 'top'
                text_size: self.size
                color: (0.4, 0.4, 0.4, 1)