#: include app/interface/kvLang/Components.kv

<TasksPage>:
    name: ('taskspage')
    BGwhiteGreen:
        id: taskslayout
        FloatLayout:
            size_hint_y: 0.09
            orientation: 'vertical'
            ActionBar:
                pos_hint: {'top': 1}
                ActionView:
                    ActionPrevious:
                        on_release: app.root.current='homepage'

        BoxLayout:
            orientation: 'vertical' 
            size_hint_y: None 
            height: 100
            spacing: 10

            Label:
                size_hint_y: 0.5
                text: 'Tarefas da família'
                halign: 'left'
                text_size: self.size
                font_size: 24
                padding: [10,0]
                color: (0,0,0,1)

            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: 0.5

                Image:
                    size_hint_x: 0.5
                    id: taskImage
                    source: 'dev/static/images/ui_user_profile_avatar_person_icon_208734.png'
                
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 2
                    Label:
                        id: nucleoTitle
                        text: "nome núcleo"
                        font_size: 20
                        halign: 'left'
                        text_size: self.size
                        color: (0, 0, 0, 1)

                    Label:
                        id: nucleoDescription
                        text: "descrição"
                        halign: 'left'
                        valign: 'top'
                        text_size: self.size
                        color: (0.4, 0.4, 0.4, 1)

                    
        ScrollView:
            do_scroll_x: False 
            #size_hint_y: None
            
            BoxLayout:
                id: containerTasks
                orientation: 'vertical'
                padding: 5
                spacing: 5
                size_hint_y: None
                height: self.minimum_height
       

        BoxLayout:
            size_hint_y: 0.1
            padding: [60, 4]
            
            EnterButton:
                text: 'criar tarefa'
                on_release: root.insertModal()
                
